- README.md
- src/Client.php
- tests/ClientTestCase.php
- tests/MaintainersTest.php
- tests/ProjectsTest.php
- tests/StorageBackendTest.php
- remove mysql backend
- separate maintainer for running tests
- organizations and projects cleanup on tests start in tests maintainer
- don't allow to run tests against production hosts
- URL parametr of client is required
> snowflake backend is default, mysql removed

- apiary.apib
- src/Client.php
- tests/UsersTest.php
Regarding: https://github.com/keboola/connection/issues/1109
Caution: this is just how it could work in my imagination.  It may be the case that this is the type of thing that can't be tested and that this kind of bypass is too risky.
Proposed changes:
- add endpoint `/manage/users/[user_id_or_email]/mfa` for `POST` with `secret` for enable and `DELETE` for disable
> Super Admin - Disable MFA

- apiary.apib
Je na zváženou jestli endpoint na vypínání MFA má vracet 204 (Header: No content) a ostatní requesty vracejí 200 a detail uživatele. In My Humple Opinion by je lepší vracet detail všeho, aby člověk viděl, že se to změnilo a nemusel dělat "get detail" request.
Doplnil jsem ještě Response u předchozích metod, protože všechny využívají jednu metodu pro generování response.
Dokumentuje endpoint: https://github.com/keboola/connection/pull/1676
> Apib - endpoint for removing superadmin privilege

- docker-compose.yml
Docker-compose.yml by měl mít taky externí síť, aby se dala používat adresa http://connection-apache
> Refactoring: external network 

- apiary.apib
- src/Client.php
- tests/ClientTestCase.php
- tests/MaintainerInvitationsTest.php
- tests/MaintainerJoinTest.php
- tests/MaintainersTest.php
- tests/OrganizationInvitationsTest.php
- tests/OrganizationJoinTest.php
- tests/OrganizationsTest.php
- tests/ProjectInvitationsTest.php
- tests/ProjectJoinRequestsTest.php
- tests/ProjectJoinTest.php
- tests/ProjectsTest.php
Pozvanky do organizace:
- rozsireni klienta
- testy
- update apiary dokumentace
Zaroven jsem trochu preskladal testy pozvanek a join requestu organizace a projektu:
- `findProjectUser()` + `findOrganizationMember()` + `findMaintainerMember()` presunuto do `ClientTestCase`
- uprava init prostredi v `setUp()` _(diky novemu limitu na min. 1 clena maintanera)_
> Maintainer invitations

- tests/ProjectInvitationsTest.php
V puvodnim PR https://github.com/keboola/kbc-manage-api-php-client/pull/74 byla chybka v testech ktera rozbila build connection
Test zve `normalUsera` do projektu a ten si pak ma schvalit pozvanku.
> fixup: testInvitationAttributesPropagationToProjectMembership

- apiary.apib
- src/Backend.php
- tests/BackendTest.php
- tests/FileStorageAbsTest.php
- tests/ProjectsTest.php
- tests/StorageBackendTest.php
updated tests:
- `ProjectsTest::testCreateProjectWithRedshiftBackend` -> `ProjectsTest::testCreateProjectWithBackend` added dataprovider with redshift|snowflake|synapse
- `StorageBackendTest::testStorageAssignRedshiftBackend` -> `StorageBackendTest::testStorageAssignBackend` added dataprovider with redshift|synapse
New class `Backend` which contains constants with backend names
Updated apib file with endpoint definition
Možné přidat až s https://github.com/keboola/connection/pull/2369
> KBC-177 synapse backend tests

- tests/ProjectDeleteTest.php
Zvyseni purge timeoutu. Casto nam nestiha dobehnout do dvou minut kdyz poustime testy paralelne.
> ProjectDeleteTest::testDeleteAndPurgeProjectWithData purge timeout 5 minutes

- src/Exception.php
Nema to zadne issue v Jire. Vsiml jsem si toho, kdyz mi PHPStan zacal rvat, ze $message muze byt jen null.
Stejny problem jako https://github.com/keboola/storage-api-php-client/pull/635
> Fix Exception constructor parameters types (in phpDoc)

- tests/ProjectsTest.php
- tests/StorageBackendTest.php
Jira: KBC-1982
Spadle testy:
```
11:50:24-UTC - manage                             -	1) Keboola\ManageApiTest\ProjectsTest::testProjectDataRetention
11:50:24-UTC - manage                             -	Failed asserting that 1 matches expected 7.
```
```
11:50:24-UTC - manage                             -	1) Keboola\ManageApiTest\StorageBackendTest::testCreateStorageBackend with data set "snowflake" (array('snowflake', 'keboolaconnectiondev.us-east-...ng.com', 'DEV', '[secure]', '[secure]', 'us-east-1', 'keboola'))
11:50:24-UTC - manage                             -	Keboola\ManageApi\ClientException: Application error.
odbc_prepare(): SQL error: SQL compilation error:\nExceeds maximum allowable retention time (1)., SQL state 22023 in SQLPrepare
```
> KBC-1982 fix dataRetentionTimeInDays

- tests/ProjectsTest.php
Nejde nastavit u limitovaného backendu 30, jen 1 nebo 0, tak jsem dal nulu :)
> Fix data retention for limited SNFLK backend

- apiary.apib
u endpointu [Create Feature](https://keboolamanagementapi.docs.apiary.io/#reference/super-features/features/create-a-feature) se zobrazoval parametr v `url`, i kdyz je v JSONu.
> show type parameter only for retrieve all call

- tests/ProjectsTest.php
disable testing of creating new EXA projects until EXA won't be enabled again https://github.com/keboola/connection/pull/3523 (it doesnt start the DBs on the beginning of the build)
> Disable creating EXA projects until EXA will re-enabled again

- tests/CommonTest.php
- tests/FeaturesTest.php
- tests/MaintainerInvitationsTest.php
- tests/MaintainerJoinTest.php
- tests/MaintainersTest.php
- tests/OrganizationInvitationsTest.php
- tests/OrganizationJoinMfaValidationTest.php
- tests/OrganizationMfaValidationTest.php
- tests/OrganizationsTest.php
- tests/ProjectInvitationsMfaValidationTest.php
- tests/ProjectInvitationsTest.php
- tests/ProjectJoinMfaValidationTest.php
- tests/ProjectJoinRequestsMfaValidationTest.php
- tests/ProjectJoinRequestsTest.php
- tests/ProjectJoinTest.php
- tests/ProjectMembershipRolesTest.php
- tests/ProjectMfaValidationTest.php
- tests/ProjectTemplatesTest.php
- tests/ProjectsMetadataTest.php
- tests/ProjectsTest.php
- tests/StorageBackendTest.php
```
17:10:52-UTC - manage                             -	There were 88 warnings:
17:10:52-UTC - manage                             -	
17:10:52-UTC - manage                             -	1) Keboola\ManageApiTest\CommonTest::testVerifyAdminToken
17:10:52-UTC - manage                             -	assertInternalType() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assertIsInt() instead.
17:10:52-UTC - manage                             -	assertInternalType() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assertIsArray() instead.
17:10:52-UTC - manage                             -	
17:10:52-UTC - manage                             -	2) Keboola\ManageApiTest\CommonTest::testVerifySuperToken
17:10:52-UTC - manage                             - …
```
> Update deprecated phpunit asserts

- tests/ProjectsTest.php
Protoze se tady "jen" kontroluje, zda tam neco je, tak by melo stacit kontrolovat misto striktniho vyzadovani `float`, jestli je to cislo `numeric`.
Test na kontrolu `float` je napr `testSuperAdminCanGiveProjectCredits`.
> fix float paygo credits

- composer.json
Jira: https://keboola.atlassian.net/browse/PS-3279
Related to https://github.com/keboola/storage-api-php-client/pull/784
Allow using with Guzzle 7.
Guzzle has some breaking changes (https://github.com/guzzle/guzzle/blob/7.0.0/UPGRADING.md#60-to-70) but everything seems to work for me so far.
> PS-3279 Support Guzzle 7

- apiary.apib
rozdil je jen v tom, ze `Organization` model obsahuje pole projektu, zatimco tento endpoint je nema
> Fix documentation of listing orgs

- tests/FeaturesTest.php
Jira: CT-352
Connection PR: -
---
v conention jsme nasli, ze to je opraveny, tak jen pridavam test
> CT-352 test missing ID wont be a problem anymore

- apiary.apib
- openapi.yml
- tests/ProjectDeleteTest.php
- tests/ProjectsTest.php
Jira: [CT-1402](https://keboola.atlassian.net/browse/CT-1402)
Connection PR: https://github.com/keboola/connection/pull/5052
---
[CT-1402]: https://keboola.atlassian.net/browse/CT-1402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1402 fix2 token management endpoint

- tests/ProjectTemplateFeaturesAssigningTest.php
Jira: CT-XXX
---
Po tom ako sme pridali featuru do templaty migraciou zacal padat tento test, tak som ho zmazal nic take realne netestoval https://github.com/keboola/kbc-manage-api-php-client/pull/169#pullrequestreview-855317992
> remove test testCreateProjectWithROIMFeatureFromTemplate

- tests/ProjectStorageBackendTest.php
Jira: CT-XXX
---
I was looking for redshift projects on e2e and I found tons of maintainers and orgs -> this test does not clean after itself, so it should. There is no need for extra logic. if it fails and there will be an extra maintainer/org, nothing would happen
> clean org and maintainer at the end of the test

- apiary.apib
- tests/UiAppsTest.php
Jira: CT-1944
Connection PR: keboola/connection#5450
- ~~[ ] New client method(s) has tests~~ No new client method
- ~~[ ] Apiary file is updated~~ In Apiary there is no mention of menifest file structure
---
New test checking if new _isCritical_ flag in _manage/ui-apps_  is: 
- returned when app is registered
- returned in list of apps
> [CT-1944] Add test of new ui-apps isCritical flag
