keboola/kbc-manage-api-php-client

README.md
tests/ProjectsTest.php

Test for adding / removing administrators to projects with reason and expiration.

Expiring admins

---

Dockerfile
README.md
docker-compose.yml

I added `Dockerfile`, `docker-compose.yml` file and updated README, so tests in container can be ran with ease.

Tests in docker - revised

---

src/Client.php
tests/ProjectsTest.php

Test for:
- un-delete active projects
- reset project expiration on un-delete
- project expiration set on un-delete

Projects undelete test

---

src/Client.php
tests/ClientTestCase.php
tests/FeaturesTest.php
tests/ProjectsTest.php
tests/UsersTest.php

Suvisiaca issue v Connection: https://github.com/keboola/connection/issues/260
--
Tasks:
potom, az to hore bude implemented aj na connection, asi by som poriesil aj:

WIP - tests for features

---

tests/FeaturesTest.php

Test for wrong feature type

---

src/Client.php
tests/OrganizationsTest.php

Test for manage/organisation/{id}

Organizations

---

apiary.apib
src/Client.php
tests/OrganizationsTest.php

Re: https://github.com/keboola/connection/pull/633

Admin approval

---

tests/OrganizationsTest.php

https://github.com/keboola/connection/issues/697

test: superAdmin can add user to org if allowAutoJoin is true

---

tests/ClientTestCase.php
tests/ProjectsTest.php

Issue: https://github.com/keboola/kbc-manage-api-php-client/pull/26
Connection fix: https://github.com/keboola/connection/pull/776

Test for expiring admin in deleted project

---

apiary.apib
tests/ProjectsTest.php

ref: https://github.com/keboola/connection/issues/1040
Set data retention period attribute for project.

Project setting data retention

---

apiary.apib
src/Client.php
tests/ProjectTemplateFeaturesTest.php

Changes:
- New "project template features" client methods
- Tests
- Docs

Project template features

---

apiary.apib

Editovala jsem to jenom jako text. Nekompilovala jsem to do webovy stranky, jak jsem zvykla u dokumentace. U apiary to neumim :-).
Nevim, kam nalinkovat ` Read more in Components Management.` (radek 34 ).
dik!

management api - texts edits

---

apiary.apib
src/Client.php
tests/MaintainersTest.php
tests/OrganizationsTest.php
tests/ProjectJoinRequestsTest.php
tests/ProjectJoinTest.php
tests/ProjectsTest.php

Podpora a testy pro rozšíření KBC o žádosti vstupu do projektu: https://github.com/keboola/connection/pull/1579

Project Join Request

---

apiary.apib
src/Client.php
tests/ProjectInvitationsTest.php
tests/ProjectJoinRequestsTest.php
tests/ProjectJoinTest.php
tests/ProjectsTest.php

Apiary update + testy + rozsireni klienta o pozvanky do projektu:
https://github.com/keboola/connection/pull/1611

Projects Invitations

---

apiary.apib
tests/ProjectsTest.php

Changes:
- new test for setting project desc. on creation
- update docs (includes also previous update for updating project desc)

Project create with desc

---

apiary.apib
tests/MaintainersTest.php
tests/OrganizationInvitationsTest.php
tests/OrganizationJoinTest.php
tests/OrganizationsTest.php
tests/ProjectInvitationsTest.php
tests/ProjectJoinRequestsTest.php
tests/ProjectJoinTest.php
tests/ProjectsTest.php

Testy na minimalni pocet clenu v organizaci a prava na zakladani noveho projektu

Organization restrictions

---

tests/ProjectsTest.php

https://github.com/keboola/connection/pull/1755

tests: last member can leave project

---

docker-compose.yml
docker/xdebug/.gitignore
docker/xdebug/Dockerfile
docker/xdebug/xdebug.ini.dist

Vytáhnul jsem "xdebug init" commit z https://github.com/keboola/kbc-manage-api-php-client/pull/61. Bylo to nějak moc souborů a ještě konflikt, protože jsem nějak špatně vytvořil PR.

Xdebug init

---

apiary.apib
tests/OrganizationsTest.php

Organization CRM ID

---

tests/UsersTest.php

Tests https://github.com/keboola/connection/pull/1929

Test removing user from organization fails for last user

---

apiary.apib
docker-compose.yml
src/Client.php
tests/ClientMfaTestCase.php
tests/OrganizationJoinMfaValidationTest.php
tests/OrganizationMfaValidationTest.php
tests/ProjectInvitationsMfaValidationTest.php
tests/ProjectJoinMfaValidationTest.php
tests/ProjectJoinRequestsMfaValidationTest.php
tests/ProjectMfaValidationTest.php

Testy pro https://github.com/keboola/connection/pull/1995

force mfa and lock membership

---

tests/ProjectsTest.php

Testy pro PR https://github.com/keboola/connection/pull/1948

new privilege canPurgeTrash for sapi tokens

---

apiary.apib
src/Client.php
tests/ProjectsTest.php

Fixies https://github.com/keboola/connection/issues/1945
Main PR: https://github.com/keboola/connection/pull/2048

Add api call for remove project limit

---

tests/ProjectsTest.php

tests: project enable/disable

---

apiary.apib
src/Client.php
tests/ProjectInvitationsTest.php
tests/ProjectMembershipRolesTest.php
tests/ProjectsTest.php

Nová možnost nastavovat role uživatelů v projektu
- update apiary
- volitelný atribut role při pozvání přidání usera do projektu
- nový api call pro změnu role v projektu

project membership roles

---

apiary.apib
src/Client.php
tests/ProjectTemplatesTest.php

Solves https://github.com/keboola/connection/issues/2145

Add project templates detail/list

---

tests/ProjectTemplatesTest.php

Solves https://github.com/keboola/connection/pull/2226

Check template values type

---

apiary.apib
src/Client.php
tests/ListProjectsUsersTest.php
tests/OrganizationMfaValidationTest.php

Main PR: https://github.com/keboola/connection/pull/2276
JIRA Issue: https://keboola.atlassian.net/browse/KBC-31

Pridanie endpointu projects-users

---

apiary.apib
src/Backend.php
tests/BackendTest.php
tests/FileStorageAbsTest.php
tests/ProjectsTest.php
tests/StorageBackendTest.php

Reverts keboola/kbc-manage-api-php-client#94
JIRA: https://keboola.atlassian.net/browse/KBC-198
updated tests:
ProjectsTest::testCreateProjectWithRedshiftBackend -> ProjectsTest::testCreateProjectWithBackend added dataprovider with redshift|snowflake|synapse
StorageBackendTest::testStorageAssignRedshiftBackend -> StorageBackendTest::testStorageAssignBackend added dataprovider with redshift|synapse
New class Backend which contains constants with backend names
Updated apib file with endpoint definition

KBC-198 synapse backend tests

---

apiary.apib

Oprava url pro seznam sablon projektu
https://github.com/keboola/kbc-manage-api-php-client/blob/2eb4c080b7a2be3bc0a47661c687a6312efc7856/src/Client.php#L535

apiary.apib - fixup project templates list

---

tests/ProjectJoinTest.php

Is testing https://github.com/keboola/connection/pull/2448

tests: create storage token with autojoin validation

---

apiary.apib
tests/ProjectsTest.php

JIRA story: https://keboola.atlassian.net/browse/KBC-377
Main PR: keboola/connection#2461

KBC-377 test can't able to canUseDirectAccess set to true

---

apiary.apib

Tak este jednou :D omylom som to mergol do inej vetve :/

Update tokens response parameters

---

.travis.yml
deploy-tag.sh
tests/ProjectDeleteTest.php
tests/_data/users.csv

https://keboola.atlassian.net/browse/KBC-303

testDeleteAndPurgeProjectWithData for all backends

---

tests/ProjectDeleteTest.php

KBC: https://github.com/keboola/connection/pull/2498

[Synapse] KBC-386 part 2 Assign and InitBucket update

---

tests/ProjectsTest.php
tests/StorageBackendTest.php

KBC: https://github.com/keboola/connection/pull/2566

KBC-541 add testUnsupportedFileStorageForBackend test

---

apiary.apib
tests/ProjectsTest.php

Pay As You Go info in project details if the project is configured as paygo
```json
{
"payAsYouGo": {
"purchasedCredits": 123
}
}
```

tests: paygo info in project details

---

tests/ProjectsTest.php

KBC: https://github.com/keboola/connection/pull/2672
JIRA: https://keboola.atlassian.net/browse/KBC-728

KBC-728 add test addUserToProject with empty email

---

tests/MaintainersTest.php

KBC: https://github.com/keboola/connection/pull/2658

KBC-359 add test when createMaintainer call is invalid

---

apiary.apib

JIRA: https://keboola.atlassian.net/browse/KBC-801
KBC: https://github.com/keboola/connection/pull/2726

KBC-801 update api documentation for synapse useSynapseManagedIdentity

---

tests/ProjectsTest.php

https://github.com/keboola/connection/pull/2754#issuecomment-696568165

make ProjectsTest::testAddRemoveProjectFeatures more stable

---

docker-compose.yml
src/Client.php
tests/ClientMfaTestCase.php
tests/ClientTestCase.php
tests/CommonTest.php
tests/NotificationsTest.php
tests/ProjectsTest.php
tests/UiAppsTest.php

enhance userAgent for Client for better debugging

---

apiary.apib
src/Client.php
tests/ProjectsTest.php

PR https://github.com/keboola/connection/pull/2752

Client::giveProjectCredits

---

tests/ClientTestCase.php
tests/ProjectsTest.php

SLACK: https://keboola.slack.com/archives/CFVRE56UA/p1600959730047700?thread_ts=1600944572.025800&cid=CFVRE56UA

fix storage client in project test

---

tests/ProjectDeleteTest.php

Main PR: https://github.com/keboola/connection/pull/2812

KBC-932 Test delete invitation and join reuquest when project purged

---

apiary.apib
src/ProjectRole.php
tests/ProjectInvitationsTest.php
tests/ProjectMembershipRolesTest.php
tests/ProjectsTest.php

PR: https://github.com/keboola/connection/pull/2846

Share Role

---

tests/ClientTestCase.php

Switched (fixed) project and token ID logs KBC-1124

KBC-1124 Switch project and token ID

---

apiary.apib
src/Client.php
tests/ClientMfaTestCase.php
tests/ClientTestCase.php
tests/ProjectInvitationsTest.php
tests/ProjectJoinRequestsTest.php
tests/ProjectJoinTest.php
tests/ProjectsMetadataTest.php

Main PR: https://github.com/keboola/connection/pull/3063

KBC-791 create metadata for project

---

apiary.apib
src/Client.php
tests/ProjectsMetadataTest.php

Main PR: https://github.com/keboola/connection/pull/3067

KBC-846 list project metadata

---

apiary.apib
tests/ProjectsMetadataTest.php

MainPR: https://github.com/keboola/connection/pull/3069

Kbc 792 system project metadata

---

apiary.apib
src/Client.php
tests/ProjectsMetadataTest.php

Mazani metadat projektu
KBC PR https://github.com/keboola/connection/pull/3112

Delete project metadata

---

tests/ProjectDeleteTest.php

calls project purge for project which has some metadata. Then you can check manually that metadata were erased
Connection PR https://github.com/keboola/connection/pull/3116

KBC-793 test for deleting metadata from purged projects

---

apiary.apib
tests/ProjectsMetadataTest.php

Main PR: https://github.com/keboola/connection/pull/3126

KBC-1371 allow view metadata for guest and read only role

---

apiary.apib

Jira: https://keboola.atlassian.net/browse/KBC-1395

KBC-1395 Add apiary docs for List projects for an organization endpoint

---

apiary.apib
src/Client.php
tests/OrganizationsMetadataTest.php
tests/ProjectsMetadataTest.php

Jira: https://keboola.atlassian.net/browse/KBC-1429
Connection PR https://github.com/keboola/connection/pull/3145
Apiary docs for new endpoints 
- POST manage/organizations/{$organizationId}/metadata
- GET /manage/organizations/{$organizationId}/metadata
Tests for
- create org metadata
- list org metadata

KBC-1429 test creating organization metadata

---

apiary.apib
src/Client.php
tests/OrganizationsMetadataTest.php

Jira: https://keboola.atlassian.net/browse/KBC-1432
Connection: https://github.com/keboola/connection/pull/3179

KBC-1432 delete org metadata

---

src/Client.php
tests/OrganizationsTest.php

https://keboola.atlassian.net/browse/KBC-1497
https://keboola.slack.com/archives/C01DQ9VRQK0/p1619687933000200

Stabilize tests

---

src/Client.php

Jira: KBC-1498
Prislo mi hloupy vsude mit
```php
$emailOrId = urlencode($emailOrId);
```
tak jsem pridal funkci `encode`, ktera se simuluje chovani `sprintf`
```php
return $this->apiGet($this->encode('/manage/users/%s', $emailOrId));
```
Je to pro vás čitelný?
Problem by nemel byt ani v jinym jazycich pri pripadnym generovani (Java, Python...).

KBC-1498 escape url parameters

---

apiary.apib

Upravujem dokumentaciu, nevsimol som si pri review

Fix apiary

---

apiary.apib
src/Client.php
tests/ClientTestCase.php
tests/MaintainersMetadataTest.php

Jira: https://keboola.atlassian.net/browse/KBC-1594 (vsechny tikety)
Connection: https://github.com/keboola/connection/pull/3254

KBC-1595 Maintainers metadata

---

apiary.apib
src/Client.php
tests/StorageBackendTest.php

Main PR: https://github.com/keboola/connection/pull/3278

KBC-1625 update storage backend

---

src/Client.php
tests/StorageBackendTest.php

Jira: https://keboola.atlassian.net/browse/KBC-1632
Test: https://github.com/keboola/connection/pull/3284

KBC-1632 remove list logins

---

apiary.apib

Este som zabudol upravit response v dokumentacii list storage backend

add username to list response

---

tests/OrganizationsMetadataTest.php
tests/ProjectsMetadataTest.php

Jira: KBC-1667
Connection: https://github.com/keboola/connection/pull/3302

KBC-1667 add feature saml-metadata-access

---

src/Client.php
tests/SessionTokensTest.php

Changes:
- Add method to generate session token (`createSessionToken`)
- Add tests

Tests for Session Tokens

---

tests/ProjectInvitationsTest.php

KBC-1708 
Code: https://github.com/keboola/connection/pull/3333

KBC-1708 Test adding invalid emails to project

---

tests/ClientMfaTestCase.php
tests/ListProjectsUsersTest.php
tests/MaintainerInvitationsTest.php
tests/MaintainerJoinTest.php
tests/MaintainersMetadataTest.php
tests/OrganizationInvitationsTest.php
tests/OrganizationJoinTest.php
tests/OrganizationsMetadataTest.php
tests/OrganizationsTest.php
tests/ProjectInvitationsTest.php
tests/ProjectJoinRequestsTest.php
tests/ProjectJoinTest.php
tests/ProjectMembershipRolesTest.php
tests/ProjectTemplatesTest.php
tests/ProjectsMetadataTest.php
tests/ProjectsTest.php
tests/PromoCodesTest.php
tests/SessionTokensTest.php
tests/UsersTest.php

Jira: https://keboola.atlassian.net/browse/KBC-1330
Testy OK: https://github.com/keboola/connection/pull/3353

KBC-1330 replace email spam@keboola.com

---

apiary.apib
src/Backend.php
tests/MaintainersTest.php
tests/ProjectDeleteTest.php
tests/ProjectStorageBackendTest.php
tests/ProjectsTest.php

Only api docs update where exasol and synapse were missing

Exasol table

---

apiary.apib
src/Backend.php
tests/MaintainersTest.php
tests/ProjectDeleteTest.php
tests/ProjectStorageBackendTest.php
tests/ProjectsTest.php

KBC: https://github.com/keboola/connection/pull/3327
testDeleteAndPurgeProjectWithData je skipped protože sa tam volá createTable
testProjectStorageAssignBackend je skipped protože volá createBucket

Exasol assign test

---

apiary.apib
src/Backend.php
tests/MaintainersTest.php
tests/ProjectDeleteTest.php
tests/ProjectStorageBackendTest.php
tests/ProjectsTest.php

KBC: https://github.com/keboola/connection/pull/3332

Exasol bucket

---

tests/ProjectStorageBackendTest.php

KBC-1907 Disable exasol testing in MAPI

---

tests/ProjectDeleteTest.php
tests/ProjectJoinTest.php
tests/ProjectStorageBackendTest.php
tests/ProjectTemplateFeaturesAssigningTest.php
tests/ProjectsTest.php
tests/SessionTokensTest.php
tests/UsersTest.php

Jira: KBC-1982
Spadle testy:
```
1) Keboola\ManageApiTest\ProjectDeleteTest::testPurgeExpiredProjectRemoveJoinRequest
2) Keboola\ManageApiTest\ProjectDeleteTest::testPurgeExpiredProjectRemoveUserInvitation
3) Keboola\ManageApiTest\ProjectDeleteTest::testPurgeExpiredProjectRemoveMetadata
4) Keboola\ManageApiTest\ProjectDeleteTest::testDeleteAndPurgeProjectWithData with data set "snowflake with S3 file storage" ('snowflake', 'aws')
5) Keboola\ManageApiTest\ProjectDeleteTest::testDeleteAndPurgeProjectWithData with data set "snowflake with ABS file storage test" ('snowflake', 'azure')
6) Keboola\ManageApiTest\ProjectJoinTest::testSuperAdminCannotAddSelfToProjectRegardlessOfAllowAutoJoin with data set #0 (true)
7) Keboola\ManageApiTest\ProjectJoinTest::testSuperAdminCannotAddSelfToProjectRegard …
```

KBC-1982 add dataRetentionTimeInDays while creating project

---

tests/ProjectDeleteTest.php

Connection: https://github.com/keboola/connection/pull/3521
add testcase (via provider) for purging project which has feature `configurations-use-dev-branch-services-only`

KBC-2211 Test purging project which uses new DevConfig tables only

---

tests/ProjectDeleteTest.php

spadli testy https://app.travis-ci.com/github/keboola/connection/jobs/555956486#L7680 pretoze sme uz upravili templaty projektu takze pri zalozeni projektu uz ten projekt tu feature ma

remove test delete project with useDevBranch feature

---

composer.json
tests/ProjectTemplateFeaturesAssigningTest.php

Connection : https://github.com/keboola/connection/pull/3539
jira: KBC-2312
Just a test which adds feature to template and creates the project so new roles should be created

KBC-2312 Add test for UC when creating project with ROIM feature in template

---

tests/ProjectsTest.php

Jira: KBC-2342
Connection: https://github.com/keboola/connection/pull/3565

KBC-2342 return credits as float

---

.gitignore
tests/StorageBackendTest.php

KBC-2380 Backend flag for dynamic backends

---

tests/StorageBackendTest.php

KBC-2381
Code: https://github.com/keboola/connection/pull/3597

KBC-2381 Enable dynamic backends if backend DB has flag dynamicBackendsAllowed

---

apiary.apib

Jira: KBC-2381
Connection PR: https://github.com/keboola/connection/pull/3597
- not BC break, because new attributes are optional
---

KBC-2381 Update MAPI documentation

---

tests/StorageBackendTest.php

Jira: KBC-XXX
Connection PR: https://github.com/keboola/connection/pull/3604
---

Test if can create project after update password for storage backend

---

.gitignore
README.md
composer.json
phpunit-retry.xml.dist
tests/ClientTestCase.php

Jira: KBC-XXX
---
Urobim composer update na mastru
Ak si checkoutnem tuto branch testy musia stale robit retry 3x
vytvorim si novy file z phpunit-retry.xml.dist a pomenujem ho phpunit-retry.xml ked spustim teraz testy neurobi to retry ani jeden krat.
mozem si lubovolne upravit pocet retry pre lokal.

Roman add phpunit retry lib

---

apiary.apib

Jira: KBC-2494
Connection PR: https://github.com/keboola/connection/pull/3620
---

add teradata to api doc

---

composer.json
tests/ProjectDeleteTest.php

Jira: https://keboola.atlassian.net/browse/KBC-2517
Connection PR: https://github.com/keboola/connection/pull/3661
---

Test purge project with configurations metadata

---

tests/ClientTestCase.php
tests/ProjectDeleteTest.php
tests/bootstrap.php

Jira: KBC-2517
---
Na zaklade https://github.com/keboola/kbc-manage-api-php-client/pull/183#discussion_r838420915

Kbc 2517 add generate desc for test obj

---

.github/workflows/branch.yml
composer.json

Kbc 2545 remove vcs and use correct lib

---

apiary.apib
phpstan-baseline.neon
tests/ProjectsTest.php

Jira: KBC-2637
Connection PR: https://github.com/keboola/connection/pull/3724
---

KBC-2637 remove testing project description

---

apiary.apib
tests/ProjectsTest.php

Jira: KBC-2528
Connection PR: https://github.com/keboola/connection/pull/3761
---

remove directAccess

---

tests/StorageBackendTest.php

Jira: -
Connection PR: https://github.com/keboola/connection/pull/3772
---

Test custom exception when exasol is dead

---

AdjustOpenApi.php
apiary.apib
composer.json
openapi.yml

jira: https://keboola.atlassian.net/browse/KBC-1614
Apiary
- add json response
- make names of the endpoints unique
- add params if missing
add custom php script which
- renames some models (should be investigated later)
- adds security section
- adds stack urls
migration apiary->openapi is done via https://github.com/kminami/apib2swagger with command 
```
$ cat apiary.apib | grep -v "X-KBC-ManageApiToken:" | apib2swagger -o openapi.yml -y --open-api-3 --info-title="Manage API" 
$ php AdjustApi.php
```
Swagger ui output here https://app.swaggerhub.com/apis/jiri.semmler/ManageAPI/1 
Apiary has been validated in apiary editor and it is still valid
I am not sure if this PR should be merged or just used for demontration and discussion

Fix apiary blueprint file to be able to migrate to OpenAPI

---

phpunit.xml.dist

exclude FileStorageGcsTest.php

---

apiary.apib
tests/MaintainersTest.php

Jira: https://keboola.atlassian.net/browse/PS-3664
Connection PR: https://github.com/keboola/connection/pull/3850
---

Maintainer - default file storage

---

apiary.apib
tests/DataPlanesTest.php
tests/MaintainersTest.php

Jira: Jira: https://keboola.atlassian.net/browse/PS-3664 + https://keboola.atlassian.net/browse/PS-3662
Connection PR: https://github.com/keboola/connection/pull/3853
---

maintainer with data plane

---

apiary.apib
src/Client.php
tests/DataPlanesTest.php
tests/PromoCodesTest.php

Jira: https://keboola.atlassian.net/browse/PS-3680
Connection PR: https://github.com/keboola/connection/pull/3855
---

data plane detail support

---

apiary.apib
tests/DataPlanesTest.php
tests/MaintainersTest.php

Jira: https://keboola.atlassian.net/browse/PS-3677
Connection PR: https://github.com/keboola/connection/pull/3864
---

Manage API - Maintainer update - dataPlaneId + defaultFileStorageId

---

apiary.apib

fix texts
Jira: KBC-XXX
Connection PR: https://github.com/keboola/connection/pull/3867
---
Prisiel som na to pri registracii file storage ze pri review sa zabudlo na to ze nesedia mena parametrov :)

Add missing parameters to apiary

---

apiary.apib
tests/FileStorageAbsTest.php
tests/FileStorageGcsTest.php
tests/FileStorageS3Test.php

Jira: KBC-2819
Connection PR: https://github.com/keboola/connection/pull/3878
---

KBC-2819 SNFLK integration name for filestorage

---

tests/ProjectDeleteTest.php

Jira: KBC-XXX
Connection PR: https://github.com/keboola/connection/pull/3858
---

KBC-2777 gcs purge test

---

apiary.apib
src/Client.php
tests/ClientTestCase.php
tests/UsersMetadataTest.php

Jira: KBC-2825
Connection PR: https://github.com/keboola/connection/pull/3900
---

KBC-2825 User metadata

---

tests/ProjectDeleteTest.php
tests/ProjectStorageBackendTest.php
tests/ProjectsTest.php

Jira: KBC-2866
Connection PR:https://github.com/keboola/connection/pull/3975
---
remove all Synapse/ABS relevant tests because on the new testing, Synapse/ABS do not exist. All tested combination are replaced by Exasol/GCS

remove synapse stuff

---

apiary.apib

Jira: KBC-2938
Connection PR: 2938
---
Zatial pridavam len dokumentaciu testy pridavania backendu vytvaraju aj projekt co nemame implementovane

Add registration and update bq to doc

---

.github/workflows/branch.yml

Jira: KBC-XXX
---
Matrix se nepouzil, protoze byla spatne pojmenovana promenna.

fix tests on Github

---

.github/PULL_REQUEST_TEMPLATE.md

add release tag check to PR template

---

apiary.apib

Jira: TER-90
jsem to jen nasel kdyz jsem si zkousel listovat backendy
---

Add manage token header

---

src/Backend.php
tests/ProjectDeleteTest.php
tests/ProjectStorageBackendTest.php
tests/ProjectsTest.php

Jira: TER-92
Connection PR: https://github.com/keboola/connection/pull/4075
---

Add purge test for TD

---

tests/FeaturesTest.php

Jira: CT-871
Connection PR: https://github.com/keboola/connection/pull/4236
---

fix test, use int id instead of string

---

tests/ProjectTemplateFeaturesAssigningTest.php

Jira: KBC-XXX
---
Jeden testik mi usiel, aj ked mi teda pride zvlastne ze ta description nebola predtym povinna

Descrption is required

---

.github/PULL_REQUEST_TEMPLATE.md
tests/ClientTestCase.php
tests/UsersMetadataTest.php

Jira: CT-886
Connection PR: -
Should help with following error
```
-'test.metadata.key1'
+ 'test_metadata_key1'
```
---

CT-886 Metadata assert with sorted data

---

apiary.apib
tests/StorageBackendTest.php

Jira: CT-916
Connection PR: https://github.com/keboola/connection/pull/4254
---

Ct 916 anyone can register backend

---

apiary.apib
src/Client.php
tests/AssignAdminFeatureTest.php
tests/AssignProjectFeatureTest.php
tests/ClientTestCase.php
tests/FeaturesTest.php

Jira: CT-871
Connection PR:https://github.com/keboola/connection/pull/4235
---

Roman ct 871 add flags to feature model

---

tests/AssignProjectFeatureTest.php
tests/ProjectTemplateFeaturesTest.php

Jira: CT-871
---
Na testingu moze mat projet vdaka templatam uz nejake nastavene features takze chcem otestoval ze ci ma spravne tu pridanu featuru ktoru pridavam v testoch

Ct 871 improve tests

---

apiary.apib
tests/AssignAdminFeatureTest.php
tests/AssignProjectFeatureTest.php
tests/BaseFeatureTest.php

Jira: CT-952, CT-951
Connection PR: https://github.com/keboola/connection/pull/4282
---

test improvment of listing

---

tests/ProjectStorageBackendTest.php

comment teradata in test

---

src/ProjectRole.php
tests/ProjectWithProtectedDefaultBranchTest.php

Jira: SOX-27
Connection PR: https://github.com/keboola/connection/pull/4434
---

SOX-27 role assign

---

tests/ProjectWithProtectedDefaultBranchTest.php

Jira: SOX-192
Connection PR: https://github.com/keboola/connection/pull/4520
---

SOX-192 add testAddFeatureToProject

---

tests/OrganizationsMetadataTest.php

Jira: CT-1113
Connection PR: https://github.com/keboola/connection/pull/4639
---

CT-1113 test maintainer provider

---

apiary.apib
composer.json
tests/OrganizationsTest.php

Jira: CT-1193
Connection PR:  https://github.com/keboola/connection/pull/4773
---

CT-1193 add ac project

---

tests/MaintainersMetadataTest.php
tests/StorageBackendTest.php

Jirka fix m8 tests

---

tests/ProjectStorageBackendTest.php
tests/ProjectsTest.php

Jira: CT-XXX
Connection PR: https://github.com/keboola/connection/pull/4811
---
fixnul jsem assertovani podle file storage a nekterym testum jsem dal groupu, kterou pak [tady](https://github.com/keboola/connection/pull/4811) excluduju. cilem je, aby nektere testy nepadaly

make manage suite green

---

tests/ProjectDeleteTest.php
tests/ProjectsTest.php

Skip tests with invalid backend providers

---

apiary.apib

Jira: CT-XXX
---
zapomnel jsem to pridat do objektu organizace https://keboolaglobal.slack.com/archives/C0553EM2RGX/p1706650688795289?thread_ts=1706606700.285679&cid=C0553EM2RGX

Add crmId and activityCenterProjectId to detail of project

---

composer.json
phpstan-baseline.neon
phpstan.neon
tests/FileStorageGcsTest.php

Jira: N/A
Connection PR: N/A
---

PHPStan update

---

apiary.apib

Fix token verify path

---

apiary.apib
tests/FileStorageGcsTest.php

Jira: [CT-992](https://keboola.atlassian.net/browse/CT-992)
Connection PR: [4943](https://github.com/keboola/connection/pull/4943)
---
[CT-992]: https://keboola.atlassian.net/browse/CT-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-992 allow file storage registration for standard user

---

README.md

document scopes

---

README.md
apiary.apib
openapi.yml
tests/ProjectsTest.php

Jira: [CT-1389](https://keboola.atlassian.net/browse/CT-1389)
Connection PR: https://github.com/keboola/connection/pull/4989
---
[CT-1389]: https://keboola.atlassian.net/browse/CT-1389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1398 - update project response test

---

tests/ProjectsTest.php

create backend only for snowflake
Jira: [CT-1398](https://keboola.atlassian.net/browse/CT-1389)
Connection PR: https://github.com/keboola/connection/pull/4989
---

CT-1398 - fix: testCreateProjectWithBackend

---

tests/BackendConfigurationProviderTrait.php
tests/ProjectStorageBackendTest.php
tests/StorageBackendTest.php

Jira: [CT-1386](https://keboola.atlassian.net/browse/CT-1386)
Connection PR: https://github.com/keboola/connection/pull/4992
---
[CT-1386]: https://keboola.atlassian.net/browse/CT-1386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1386 - backend assing test when string is passed in request

---

apiary.apib
openapi.yml
tests/ProjectDeleteTest.php
tests/ProjectsTest.php

Jira: [CT-14052](https://keboola.atlassian.net/browse/CT-1402)
Connection PR: https://github.com/keboola/connection/pull/5011
---

CT-1402 - Create storage token management endpoint tests

---

apiary.apib
openapi.yml
tests/ProjectDeleteTest.php
tests/ProjectsTest.php

Reverts keboola/kbc-manage-api-php-client#247

Revert "CT-1402 - Create storage token management endpoint tests"

---

tests/ProjectStorageBackendTest.php

Jira: CT-XXX
Connection PR: https://github.com/keboola/connection/pull/5138
---

test assing backend twice should fail

---

tests/AssignProjectFeatureTest.php

Jira: [CT-1524](https://keboola.atlassian.net/browse/CT-1524)
Connection PR: https://github.com/keboola/connection/pull/5183
---
[CT-1524]: https://keboola.atlassian.net/browse/CT-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1524 fix feature assign

---

.github/workflows/branch.yml
.github/workflows/master.yml
.github/workflows/tag.yml

Jira: CT-XXX
---
https://github.com/keboola/kbc-manage-api-php-client/actions/runs/10270820290/job/28419421457
```
Run docker-compose build --build-arg PHP_VERSION=7.4 release
/home/runner/work/_temp/93ee9[7](https://github.com/keboola/kbc-manage-api-php-client/actions/runs/10270820290/job/28419421457#step:3:8)f4-6285-4827-8e59-8f19788bc6be.sh: line 1: docker-compose: command not found
Error: Process completed with exit code 127.
```

docker-compose => docker composer

---

apiary.apib
openapi.yml
tests/ProjectTemplatesTest.php

- Jira: CT-1700
- Connection PR: https://github.com/keboola/connection/pull/5224
---
Changes:
- update tests to reflect that `defaultBackend` is returned from the API from project templates

Update tests and API doc files

---

tests/ProjectsTest.php

Jira: [CT-1703](https://keboola.atlassian.net/browse/CT-1703)
Connection PR: https://github.com/keboola/connection/pull/5228
---
[CT-1703]: https://keboola.atlassian.net/browse/CT-1703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1703 - user with can-edit-project-settings feature user update tests

---

tests/ProjectsTest.php

Jira: [CT-1703](https://keboola.atlassian.net/browse/CT-1703)
Connection PR: https://github.com/keboola/connection/pull/5232
---
[CT-1703]: https://keboola.atlassian.net/browse/CT-1703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1703 - dataRetentionTimeInDays must be 1 on E2E

---

tests/ProjectMembershipRolesTest.php

Jira: [CT-1703](https://keboola.atlassian.net/browse/CT-1703)
---
[CT-1703]: https://keboola.atlassian.net/browse/CT-1703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1703 - fix tests 2

---

tests/ProjectStorageBackendTest.php

Jira: CT-1508
Connection PR: https://github.com/keboola/connection/pull/5193
---

CT-1508 update error message

---

tests/ProjectsTest.php

Jira: CT-1521
Connection PR: https://github.com/keboola/connection/pull/5240
---

CT-1521 test listing deleted project with user feature

---

apiary.apib
openapi.yml

Jira: [CT-1705](https://keboola.atlassian.net/browse/CT-1705)
Connection PR: https://github.com/keboola/connection/pull/5231
---
[CT-1705]: https://keboola.atlassian.net/browse/CT-1705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1705 update project-settings documentation

---

apiary.apib
tests/ProjectsTest.php

Jira: CT-1522
Connection PR: https://github.com/keboola/connection/pull/5314
---

CT-1522 Support enablement deleted projects cancel deletion

---

apiary.apib
tests/ProjectsTest.php

Jira: CT-1520
Connection PR: https://github.com/keboola/connection/pull/5323
---
test getDeletedProject for user feature

CT-1520 deleted projects detail tests

---

tests/AssignProjectFeatureTest.php
tests/ProjectWithProtectedDefaultBranchTest.php

Jira: CT-1782
Connection PR: https://github.com/keboola/connection/pull/5342
---

CT-1782 fix permissions issues

---

.github/workflows/branch.yml
Dockerfile
README.md
composer.json
docker/xdebug/Dockerfile
phpstan.neon

CT-323 update mapi client to php8.1-8.3

---

apiary.apib
src/Client.php
tests/StorageBackendTest.php

Jira: CT-1926
Connection PR: https://github.com/keboola/connection/pull/5449
---
- new endpoint storage backend detail

CT-1926 add Backend detail endpoint

---

tests/StorageBackendTest.php

Jira: CT-1968
Connection PR:  https://github.com/keboola/connection/pull/5467
---

Ct 1968 add support use cert : Fix err msg

---

tests/StorageBackendTest.php

Jira: -
Connection PR: -
---
ten backend se na konci nemaze a hromadi se tam storage backendy

drop storage backend at the end

---

tests/ProjectDeleteTest.php
tests/ProjectStorageBackendTest.php
tests/ProjectsTest.php
tests/StorageBackendTest.php

Jira: CT-XXX  
Connection PR: XXXXX  
---
just remove test cases fo exasol

Drop Exasol tests

---

src/Client.php
tests/ClientTestCase.php
tests/FeaturesTest.php
tests/OrganizationMfaValidationTest.php
tests/OrganizationsTest.php
tests/ProjectMfaValidationTest.php
tests/ProjectsTest.php
tests/UsersTest.php

Jira: https://keboola.atlassian.net/browse/KAB-819
Adding array shape & type hint for verifyToken. Should not be a BC break.
---

add array shape and return value

---

apiary.apib
openapi.yml
tests/MaintainersTest.php
tests/PromoCodesTest.php

Jira: [CT-2041](https://keboola.atlassian.net/browse/CT-2041)
Connection PR: https://github.com/keboola/connection/pull/5593
---
davam to ako major kedze mazeme EPs (tak ako som oznacil aj minuly PR)
[CT-2041]: https://keboola.atlassian.net/browse/CT-2041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update: CT-2041: DataPlanes remove part 2

---

apiary.apib

Jira: [CT-XXX](https://keboola.atlassian.net/browse/CT-2071)
Connection PR: [XXXXX](https://github.com/keboola/connection/pull/5684)
---

Update: CT-2071 - Manage users feature

---

apiary.apib
tests/OrganizationsTest.php

Jira: https://github.com/keboola/connection/pull/5715
Connection PR: PAT-242
---

PAT-242: Make SCOPE_ORGANIZATIONS_READ be able to also list organizations

---

apiary.apib
composer.json
phpunit.xml.dist
tests/BigqueryProjectsTest.php
tests/ClientTestCase.php
tests/ProjectMembershipRolesTest.php
tests/ProjectsTest.php

Jira: DMD-232
Connection PR:  https://github.com/keboola/connection/pull/6110
---
Pridavam test na `timezone` ze ide updatnut BQ projektu

Add timezone + test on bq backend

---

composer.json
phpstan.neon
tests/CommonTest.php
tests/MaintainersTest.php
tests/OrganizationsMetadataTest.php
tests/UiAppsTest.php

Jira: CT-XXX
---
pridavam len phpstan rule na ten  this->fail('Should fail'); v testich kde sa testuje exception a je ocakavane ze to spadne.
Tag

add phpstan rule and fix tests

---

apiary.apib
openapi.yml
phpunit.xml.dist
src/Client.php
tests/StorageBackendBigqueryTest.php
tests/StorageBackendTest.php

Jira: CT-2230
Connection PR:  https://github.com/keboola/connection/pull/6237/files
---

CT-2230 update backend
